### ISSUE TITLE
no  label10

### ISSUE THREAD

**Issue by joeygold** [microcontrollersig/reverse-engineer-led-signs#1]
org  0
jmp   label10

but label10 is not defined.

should it be label110

**Comment by microcontrollersig** [comment]
That tripped me up too. It actually says label0 (label 0).

**Comment by microcontrollersig** [comment]
Added a more verbose of the assembly here:

https://github.com/microcontrollersig/reverse-engineer-led-signs/blob/master/eeprom/eepromseansignlst.asm
